config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  resources :infos
  resources :promocaos
  resources :users
  resources :pedidos
  resources :addresses
  resources :produtos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/contato' , to: 'contatos#new'

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/showmenu', to: 'produtos#showMenu'

  post '/addtocar', to: 'produtos#addToCar'

  post '/updateStatus', to: 'pedidos#updateStatus'

  get '/quemsomos' , to: 'infos#quemSomos'
end

app/models/promocao.rb
class Promocao < ApplicationRecord
  has_many :produtos
  belongs_to :info
end

app/controllers/promocaos_controller.rb
class PromocaosController < ApplicationController
  before_action :set_promocao, only: [:show, :edit, :update, :destroy]
  before_action :impedeNaoAdmin, except: [:index]

  # GET /promocaos
  # GET /promocaos.json
  def index
    @promocaos = Promocao.all
  end

  # GET /promocaos/1
  # GET /promocaos/1.json
  def show
  end

  # GET /promocaos/new
  def new
    @promocao = Promocao.new
  end

  # GET /promocaos/1/edit
  def edit
  end

  # POST /promocaos
  # POST /promocaos.json
  def create
    @promocao = Promocao.new(promocao_params)

    respond_to do |format|
      if @promocao.save
        format.html { redirect_to @promocao, notice: 'Promocao was successfully created.' }
        format.json { render :show, status: :created, location: @promocao }
      else
        format.html { render :new }
        format.json { render json: @promocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocaos/1
  # PATCH/PUT /promocaos/1.json
  def update
    respond_to do |format|
      if @promocao.update(promocao_params)
        format.html { redirect_to @promocao, notice: 'Promocao was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocao }
      else
        format.html { render :edit }
        format.json { render json: @promocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocaos/1
  # DELETE /promocaos/1.json
  def destroy
    @promocao.destroy
    respond_to do |format|
      format.html { redirect_to promocaos_url, notice: 'Promocao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocao
      @promocao = Promocao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocao_params
      params.require(:promocao).permit(:price, :produto_id)
    end

    def impedeNaoAdmin
      if !current_user.admin
        redirect_to root_path
      end
    end
end

app/helpers/promocaos_helper.rb
module PromocaosHelper
end

app/views/promocaos/_form.html.erb
<%= form_with(model: promocao, local: true) do |form| %>
  <% if promocao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocao.errors.count, "error") %> prohibited this promocao from being saved:</h2>

      <ul>
      <% promocao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :produto_id %>
    <%= form.text_field :produto_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promocaos/edit.html.erb
<h1>Editing Promocao</h1>

<%= render 'form', promocao: @promocao %>

<%= link_to 'Show', @promocao %> |
<%= link_to 'Back', promocaos_path %>

app/views/promocaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promocaos</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocaos.each do |promocao| %>
      <tr>
        <td><%= promocao.price %></td>
        <td><%= promocao.produto %></td>
        <td><%= link_to 'Show', promocao %></td>
        <td><%= link_to 'Edit', edit_promocao_path(promocao) %></td>
        <td><%= link_to 'Destroy', promocao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocao', new_promocao_path %>

app/views/promocaos/new.html.erb
<h1>New Promocao</h1>

<%= render 'form', promocao: @promocao %>

<%= link_to 'Back', promocaos_path %>

app/views/promocaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @promocao.price %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @promocao.produto %>
</p>

<%= link_to 'Edit', edit_promocao_path(@promocao) %> |
<%= link_to 'Back', promocaos_path %>