config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  resources :infos
  resources :promocaos
  resources :users
  resources :pedidos
  resources :addresses
  resources :produtos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/contato' , to: 'contatos#new'

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/showmenu', to: 'produtos#showMenu'

  post '/addtocar', to: 'produtos#addToCar'

  post '/updateStatus', to: 'pedidos#updateStatus'

  get '/quemsomos' , to: 'infos#quemSomos'
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :impedeNaoAdmin, except: [:showMenu, :addToCar]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  def showMenu
    if !current_user.nil?
      if current_user.car.nil?
        current_user.car = Car.new
        @car = current_user.car
      else
        @car = current_user.car
      end
      @car_product = CarProduct.new
    end
    @produtos = Produto.all
  end

  def addToCar
    carProduct = CarProduct.new(car_product_params)
    carProduct.save
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:name, :description, :price)
    end
    
    def car_product_params
      params.require(:car_product).permit(:car_id, :produto_id, :quantity)
    end

    def impedeNaoAdmin
      if !current_user.admin
        redirect_to root_path
      end
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nome do produto:', class: 'form_label' %>
    <%= form.text_area :name, class: 'form_field' %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descrição', class: 'form_label' %>
    <%= form.text_area :description, class: 'form_field' %>
  </div>

  <div class="field">
    <%= form.label :price, 'Preço:', class: 'form_label' %>
    <%= form.text_field :price, class: 'form_field' %>
  </div>

  <div class="actions">
    <%= form.submit value: 'Salvar Produto', class: 'button' %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Cancelar e voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='index_title'>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome do Porduto</th>
      <th>Descrição</th>
      <th>Preço</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.name %></td>
        <td><%= produto.description %></td>
        <td><%= produto.price %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto), class: 'index_button' %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Deseja mesmo excluir?' }, class: 'index_button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1 class='index_title' >Adicionar um novo produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Voltar para Todos os Produtos', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @produto.description %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @produto.price %>
</p>

<%= link_to 'Voltar para Todos os Produtos', produtos_path %>

app/views/produtos/showMenu.html.erb
<h2>Cardápio<h2>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
      <% if !current_user.nil? %>
      <th>Quantidade</th>
      <th></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.name %></td>
        <td><%= produto.description %></td>
        <td><%= produto.price %></td>
        <td>
            <% if !current_user.nil? %>
                <%= form_with( url:'/addtocar', model: @car_product) do |form| %>
                    <%= form.number_field :quantity, class: 'input_quantity' %>
                    <%= form.hidden_field(:car_id, :value => @car.id) %>
                    <%= form.hidden_field(:produto_id, :value => produto.id) %>
                    <%= form.submit 'Adicionar ao carrinho', class: 'add_button' %>
                <%end%>
            <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if logged_in? %>
<%= link_to  "Finalizar Pedido", new_pedido_path, class:'pedido_button', id: 'button_finalizar' %>
<%end%>
<% if current_user.nil? %>
    <%= link_to  "Faça Log-in para realizar pedidos!", login_path, class:'pedido_button', id: 'button_menu_login' %>
    <%= link_to  "ou Cadastre-se já!", new_user_path, class:'pedido_button', id: 'button_menu_sign-in' %>
<%end%>