config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  resources :infos
  resources :promocaos
  resources :users
  resources :pedidos
  resources :addresses
  resources :produtos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/contato' , to: 'contatos#new'

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/showmenu', to: 'produtos#showMenu'

  post '/addtocar', to: 'produtos#addToCar'

  post '/updateStatus', to: 'pedidos#updateStatus'

  get '/quemsomos' , to: 'infos#quemSomos'
end

app/models/info.rb
class Info < ApplicationRecord
    has_many :promocaos
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  before_action :impedeNaoAdmin, except: [:getInfo, :quemSomos]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  def getInfo
    @info = Info.last
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
    if Info.find(1).nil?
      firstInfo = Info.new
      firstInfo.who = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non diam placerat, rutrum felis vel, ullamcorper ligula. Praesent eu finibus enim. Sed odio felis, feugiat quis pretium vel, tincidunt quis ante. Donec risus est, varius nec pharetra tristique, semper eu eros. Duis quis ipsum hendrerit, pharetra mi vitae, euismod neque. Cras vitae sapien vel nisi pharetra varius at non tellus. Maecenas eleifend elit neque, eu fermentum arcu vulputate non. Integer egestas placerat arcu, sed condimentum erat convallis suscipit. '
      firstInfo.email = 'pedepizza@contato.com'
      firstInfo.phone = '99999-9999'
      firstInfo.save
    end
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  def quemSomos
    if Info.last.nil?
      firstInfo = Info.new
      firstInfo.who = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non diam placerat, rutrum felis vel, ullamcorper ligula. Praesent eu finibus enim. Sed odio felis, feugiat quis pretium vel, tincidunt quis ante. Donec risus est, varius nec pharetra tristique, semper eu eros. Duis quis ipsum hendrerit, pharetra mi vitae, euismod neque. Cras vitae sapien vel nisi pharetra varius at non tellus. Maecenas eleifend elit neque, eu fermentum arcu vulputate non. Integer egestas placerat arcu, sed condimentum erat convallis suscipit. '
      firstInfo.email = 'pedepizza@contato.com'
      firstInfo.phone = '99999-9999'
      firstInfo.save
    end
    @infos = Info.last
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Informações adicionadas com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:who, :email, :phone)
    end

    def impedeNaoAdmin
      if !current_user.admin
        redirect_to root_path
      end
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_with(model: info, local: true) do |form| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :who, 'Quem somos:', class: 'form_label' %>
    <%= form.text_area :who, class:'form_field', id: 'text-area_info' %>
  </div>

  <div class="field">
    <%= form.label :email, 'E-mail de contato:', class: 'form_label' %>
    <%= form.text_field :email, class:'form_field' %>
  </div>

  <div class="field">
    <%= form.label :phone, 'Telefone de contato:', class: 'form_label' %>
    <%= form.text_field :phone, class:'form_field' %>
  </div>

  <div class="actions">
    <%= form.submit value:'Atualizar informações', class: 'button', id: 'button_info' %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1 class='index_title' >Editar informações gerais:</h1>

<%= render 'form', info: @info %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Infos</h1>

<table>
  <thead>
    <tr>
      <th>Who</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.who %></td>
        <td><%= info.email %></td>
        <td><%= info.phone %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form', info: @info %>

<%= link_to 'Back', infos_path %>

app/views/infos/quemSomos.html.erb
<section class= 'quem-somos'>
    <h3 class='quem-somos_title'>Quem somos?</h3>
    <p class='quem-somos_description'><%= @infos.who %></p>
    <%= image_tag  "food-truck.svg", class: 'quem-somos_img' %>
</section>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quem somos:</strong>
  <%= @info.who %>
</p>

<p>
  <strong>Email de contato:</strong>
  <%= @info.email %>
</p>

<p>
  <strong>Telefone de contato:</strong>
  <%= @info.phone %>
</p>

<%= link_to  "Voltar para pagina inicial", root_path %>