config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  resources :infos
  resources :promocaos
  resources :users
  resources :pedidos
  resources :addresses
  resources :produtos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/contato' , to: 'contatos#new'

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/showmenu', to: 'produtos#showMenu'

  post '/addtocar', to: 'produtos#addToCar'

  post '/updateStatus', to: 'pedidos#updateStatus'

  get '/quemsomos' , to: 'infos#quemSomos'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
end

app/models/car_product.rb
class CarProduct < ApplicationRecord
  belongs_to :car
  belongs_to :produto
end

app/models/contato.rb
class Contato < ApplicationRecord
    
end

app/models/info.rb
class Info < ApplicationRecord
    has_many :promocaos
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  has_one :car
  belongs_to :user, optional: true
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/models/promocao.rb
class Promocao < ApplicationRecord
  has_many :produtos
  belongs_to :info
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password , presence: true, length: {minimum: 6}
    has_many :pedidos
    has_one :car
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/promocaos_helper.rb
module PromocaosHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'allPages' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two|Poppins" rel="stylesheet"> 
  </head>

  <body>
    <header>
      <ul class= 'navbar-list'>
        <div class='allways-on-links'>
          <%= link_to  "Pagina inicial", root_path, class: 'header-link' %>
          <%= link_to  "Quem Somos", '/quemsomos', class: 'header-link' %>
          <%= link_to  "Contato", new_contato_path, class: 'header-link' %>
          <%= link_to  "Nosso cardapio(Faça seu pedido)", '/showmenu', class: 'header-link' %>
        </div>

        <%if !logged_in?%>
          <div class='sign-in-block'><%= link_to  "Cadastre-se", new_user_path, class: 'header-link', id: 'link-sign-in' %></div>
          <div class='login-block'><%= link_to  "Login", login_path, class: 'header-link', id: 'link-login' %></div>
        <%end%>
        <div class='admin-bar'>
          <%if logged_in? && current_user.admin%>
              <%= link_to  "Gerenciar Produtos", produtos_path, class: 'header-link' %>|
              <%= link_to  "Gerenciar Pedidos", pedidos_path, class: 'header-link' %>|
              <%= link_to  "Gerenciar Usuários", users_path, class: 'header-link' %>|
              <%= link_to  "Gerenciar Informações", edit_info_path(1), class: 'header-link' %>
          <%end%>
        </div>
        <%if logged_in?%>
          <div class='logout-block'><%= link_to  "Logout", logout_path, method: :delete, class: 'header-link', id: 'link-logout' %></div>
        <%end%>
      </ul>
    </header>
    <div class='site-body'>
    <%= yield %>
    </div>
    <footer>
      <h4 class='footer_title'>Contato</h4>
      <% infos = Info.last %>
      <p class='footer_phone'>Telefone: <%= infos.phone %></p>
      <p class='footer_email'>Email: <%= infos.email %> </p>
    </footer>
  </body>
</html>